# Generated by Django 4.2.16 on 2024-12-10 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=200)),
                ('is_chat_notif', models.BooleanField(default=False)),
                ('is_friend_notif', models.BooleanField(default=False)),
                ('is_tourn_notif', models.BooleanField(default=False)),
                ('is_match_notif', models.BooleanField(default=False)),
                ('action_by', models.CharField(default='')),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notification',
                'ordering': ['-notification_date'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('freindship_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('u_one_is_blocked_u_two', models.BooleanField(default=False)),
                ('u_two_is_blocked_u_one', models.BooleanField(default=False)),
                ('user_is_logged_in', models.IntegerField(default=0)),
                ('just_test', models.IntegerField(default=0)),
                ('user_from', models.ForeignKey(db_column='user_from', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(db_column='user_to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Friendship',
                'unique_together': {('user_from', 'user_to')},
            },
        ),
    ]
