# Generated by Django 4.2.16 on 2024-12-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_chat_notif',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_friend_notif',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_match_notif',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
