# Generated by Django 4.2.16 on 2024-12-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField()),
                ('username', models.CharField(max_length=20, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image_name', models.CharField(default='profilepng.png', max_length=50)),
                ('image_field', models.ImageField(blank=True, default='images/profilepng.png', null=True, upload_to='images/')),
                ('is_2fa', models.BooleanField(default=False)),
                ('_2fa_code', models.CharField(default='', max_length=6)),
                ('state', models.CharField(default='no state assigned', max_length=255)),
                ('is_on', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
